Here I will start exploring, cleaning. and Wrangling my EEOC1 Data

In [2]:
import pandas as pd
import dtale
import numpy as np

In [3]:
EEOC1_2023 = pd.read_csv(r"C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2023.csv")

C:\Users\jfraz\AppData\Local\Temp\ipykernel_11228\1443976776.py:1: DtypeWarning: Columns (0: Region, 1: Division, 2: State, 3: County) have mixed types. Specify dtype option on import or set low_memory=False.
  EEOC1_2023 = pd.read_csv(r"C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2023.csv")

In [4]:
EEOC1_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 105613 entries, 0 to 105612
Columns: 275 entries, Nation to TOMRF1_2
dtypes: float64(2), int64(2), str(271)
memory usage: 221.6 MB

In [5]:
EEOC1_2023.head()

,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,NAICS3_Name,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18884,18537,94570,2341332,375584,418200,267220,16434,16937,90549
1,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,NaN,...,119,42,217,4789,504,1995,176,47,19,133
2,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,Crop Production,...,51,22,111,*,106,*,90,27,13,54
3,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,Animal Production and Aquaculture,...,58,8,57,1996,346,487,59,13,5,51
4,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,Forestry and Logging,...,*,*,*,107,5,6,*,*,*,*

In [6]:
dtale.show(EEOC1_2023, open_browser=True)

In [7]:
EEOC1_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 105613 entries, 0 to 105612
Columns: 275 entries, Nation to TOMRF1_2
dtypes: float64(2), int64(2), str(271)
memory usage: 221.6 MB

In [8]:
EEOC1_2023.describe(
)

              NAICS2        NAICS3  Establishments       TOTAL10
count  101568.000000  57796.000000    1.056130e+05  1.056130e+05
mean       48.304397    481.598882    2.596430e+02  1.278511e+04
std        13.890403    131.237150    6.270791e+03  3.058448e+05
min        11.000000    111.000000    3.000000e+00  3.000000e+00
25%        42.000000    424.000000    6.000000e+00  1.380000e+02
50%        48.000000    459.000000    1.500000e+01  5.100000e+02
75%        55.000000    551.000000    5.100000e+01  2.166000e+03
max        81.000000    814.000000    1.585519e+06  7.784510e+07

In [9]:
EEOC1_2023.isnull().sum() *100/len(EEOC1_2023)

Nation        0.000000
Region        3.674737
Division      4.079043
State         4.962457
CBSA         15.482942
               ...
HISPF1_2      0.000000
ASIANF1_2     0.000000
AIANF1_2      0.000000
NHOPIF1_2     0.000000
TOMRF1_2      0.000000
Length: 275, dtype: float64

In [10]:
EEOC1_2023['State'].info(

)

<class 'pandas.Series'>
RangeIndex: 105613 entries, 0 to 105612
Series name: State
Non-Null Count   Dtype
--------------   -----
100372 non-null  str
dtypes: str(1)
memory usage: 825.2 KB

In [11]:
EEOC1_2023.dtypes

Nation       str
Region       str
Division     str
State        str
CBSA         str
            ...
HISPF1_2     str
ASIANF1_2    str
AIANF1_2     str
NHOPIF1_2    str
TOMRF1_2     str
Length: 275, dtype: object

In [12]:
EEOC1_2023['TOTAL10'].dtypes
EEOC1_2023['tomrT10']

0         2233847
1            5456
2            1721
3            1302
4              48
           ...
105608         77
105609         28
105610        101
105611         15
105612          *
Name: tomrT10, Length: 105613, dtype: str

In [13]:
EEOC1_2023['WHT1'].info()
EEOC1_2023['WHF10']

<class 'pandas.Series'>
RangeIndex: 105613 entries, 0 to 105612
Series name: WHT1
Non-Null Count   Dtype
--------------   -----
105613 non-null  str
dtypes: str(1)
memory usage: 825.2 KB

0         20331221
1            36495
2            13365
3            15923
4              680
            ...
105608        1216
105609         517
105610         361
105611          52
105612           8
Name: WHF10, Length: 105613, dtype: str

In [14]:
df = EEOC1_2023 #I got tired of typing out the full name

In [15]:
#Renaming Total_Race Variables
df.rename({
    'WHT10' : "White_Total",
    'BLKT10' : 'Black_Total',
    'HISPT10' : 'Hisp_Total',
    'ASIANT10' : 'Asian_Total',
    'AIANT10' : 'Amer_Ind_Total', 
    'NHOPIM10' : 'P_Isld_Total', 
    'tomrT10' : 'Multi_Race_Total'

}, axis=1, inplace=True)

In [16]:
#Renaming Total_Sex Variables
df.rename({
    'MT10' : 'Male_Total',
    'FT10': 'Female_Total'
}, axis=1, inplace=True)

In [17]:
#Renaming Job_Levels
df.rename({
    'TOTAL1': 'Senior_Managers', 
    'TOTAL2': 'Professionals',
    'TOTAL3': "Technicians",
    'TOTAL4': 'Sales_Workers',
    'TOTAL5': 'Clericals',
    'TOTAL6': 'Craft',
    'TOTAL7': 'Operatives',
    'TOTAL8': 'Labors',
    'TOTAL9': 'Mid_Managers'
}, axis= 1, inplace=True)

In [18]:
df['NAICS2_Name']

0                                                   NaN
1            Agriculture, Forestry, Fishing and Hunting
2            Agriculture, Forestry, Fishing and Hunting
3            Agriculture, Forestry, Fishing and Hunting
4            Agriculture, Forestry, Fishing and Hunting
                              ...
105608                Health Care and Social Assistance
105609                Health Care and Social Assistance
105610                  Accommodation and Food Services
105611    Other Services (except Public Administration)
105612    Other Services (except Public Administration)
Name: NAICS2_Name, Length: 105613, dtype: str

In [19]:
df['Year'] = 2023

In [20]:
#New Dataframe with Agg Columns Removed
df_cln = df[['Year', 'State', 'County', 'NAICS2_Name', 'Male_Total', 'Female_Total', 'White_Total','Black_Total', 'Hisp_Total',
            'Asian_Total', 'Amer_Ind_Total', 'P_Isld_Total', 'Multi_Race_Total',
            'Senior_Managers', 'Professionals', 'Technicians', 'Sales_Workers', 'Clericals', 'Craft', 'Operatives', 'Labors', 'Mid_Managers']]

In [21]:
df_cln.info()

<class 'pandas.DataFrame'>
RangeIndex: 105613 entries, 0 to 105612
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Year              105613 non-null  int64
 1   State             100372 non-null  str
 2   County            62419 non-null   str
 3   NAICS2_Name       101568 non-null  str
 4   Male_Total        105613 non-null  str
 5   Female_Total      105613 non-null  str
 6   White_Total       105613 non-null  str
 7   Black_Total       105613 non-null  str
 8   Hisp_Total        105613 non-null  str
 9   Asian_Total       105613 non-null  str
 10  Amer_Ind_Total    105613 non-null  str
 11  P_Isld_Total      105613 non-null  str
 12  Multi_Race_Total  105613 non-null  str
 13  Senior_Managers   105613 non-null  str
 14  Professionals     105613 non-null  str
 15  Technicians       105613 non-null  str
 16  Sales_Workers     105613 non-null  str
 17  Clericals         105613 non-null  str
 18  Craft             105613 non-null  str
 19  Operatives        105613 non-null  str
 20  Labors            105613 non-null  str
 21  Mid_Managers      105613 non-null  str
dtypes: int64(1), str(21)
memory usage: 17.7 MB

In [22]:
#make sure all values in Male_Total Column are a number
df_cln = df_cln.replace(['*', ''], np.nan)

In [23]:
#Change Total Columns to Int
df_cln.astype({'Male_Total': 'Int64', 'Female_Total': 'Int64', 'White_Total': 'Int64','Black_Total': 'Int64', 'Hisp_Total': 'Int64',
            'Asian_Total': 'Int64', 'Amer_Ind_Total': 'Int64', 'P_Isld_Total': 'Int64', 'Multi_Race_Total': 'Int64',
            'Senior_Managers': 'Int64', 'Professionals': 'Int64', 'Technicians': 'Int64', 'Sales_Workers': 'Int64', 
            'Clericals': 'Int64', 'Craft': 'Int64', 'Operatives': 'Int64', 'Labors': 'Int64', 'Mid_Managers': 'Int64'

})

,Year,State,County,NAICS2_Name,Male_Total,Female_Total,White_Total,Black_Total,Hisp_Total,Asian_Total,...,Multi_Race_Total,Senior_Managers,Professionals,Technicians,Sales_Workers,Clericals,Craft,Operatives,Labors,Mid_Managers
0,2023,NaN,NaN,NaN,39671364,38173733,42741322,11986834,14457050,5476881,...,2233847,1228770,17053752,4221921,9531002,8148679,3865601,7094110,6105353,12453155
1,2023,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",270931,135100,113103,30723,246872,6300,...,5456,5505,18931,14307,10298,17116,16154,60072,225197,8774
2,2023,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",108316,54489,40388,5647,111664,2236,...,1721,2378,6615,4516,7510,7421,4441,18106,94367,5273
3,2023,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",72318,39664,45576,21697,39627,2333,...,1302,1628,7431,6977,618,4363,6279,28320,44509,1367
4,2023,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",4167,940,3212,302,1439,34,...,48,118,699,92,81,401,280,1029,1793,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105608,2023,Washington,Yakima,Health Care and Social Assistance,869,3324,1687,51,2218,119,...,77,85,1501,279,8,771,39,11,26,1194
105609,2023,Washington,Yakima,Health Care and Social Assistance,301,1326,641,36,842,41,...,28,24,211,93,6,96,8,13,141,943
105610,2023,Washington,Yakima,Accommodation and Food Services,873,1121,603,34,1171,25,...,101,11,3,4,<NA>,14,<NA>,<NA>,30,1788
105611,2023,Washington,Yakima,Other Services (except Public Administration),226,167,152,4,202,10,...,15,<NA>,21,<NA>,49,64,34,87,81,12
105612,2023,Washington,Yakima,Other Services (except Public Administration),12,43,14,<NA>,38,<NA>,...,<NA>,<NA>,17,<NA>,<NA>,30,<NA>,<NA>,<NA>,<NA>

In [ ]:
# Save the dataframe to a new CSV file
df_cln.to_csv(r'C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_Cleaned_Data\EEOC1_2023_Cleaned.csv', index=False)

2026-04-22 13:00:09,435 - INFO     - Executing shutdown due to inactivity...
2026-04-22 13:00:09,449 - INFO     - Executing shutdown...
2026-04-22 13:00:09,450 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer