I am creating a function to stack all of my EEOC1 2023-2014 Dataframes into one large table.

In [1]:
import pandas as pd
from pathlib import Path
import os

In [2]:
def stack_csv(file_folder):
    folder_path = Path(file_folder)

    df_list = [pd.read_csv(file) for file in folder_path.glob('*.csv')]

    final_df = pd.concat(df_list, ignore_index=True)
    
    EEOC1_Master = final_df

    EEOC1_Master.to_csv(r'C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Cleaned_Master\EEOC1_Master.csv', index=False)

    return EEOC1_Master

my_folder = r'C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_Cleaned_Data'

final_stack = stack_csv(my_folder)
print(final_stack.head())

   Year State County                                 NAICS2_Name  Male_Total  \
0  2014   NaN    NaN                                         NaN  26728926.0
1  2014   NaN    NaN  Agriculture, Forestry, Fishing and Hunting    187857.0
2  2014   NaN    NaN  Agriculture, Forestry, Fishing and Hunting     90891.0
3  2014   NaN    NaN  Agriculture, Forestry, Fishing and Hunting     45938.0
4  2014   NaN    NaN  Agriculture, Forestry, Fishing and Hunting      2497.0

   Female_Total  White_Total  Black_Total  Hisp_Total  Asian_Total  ...  \
0    24422889.0   32348361.0    7408929.0   7066158.0    3068313.0  ...
1       90345.0      86127.0      15875.0    165020.0       7013.0  ...
2       43864.0      30544.0       3682.0     95595.0       3067.0  ...
3       22085.0      32517.0       9389.0     22823.0       2142.0  ...
4         734.0       2650.0        132.0       305.0         54.0  ...

   Multi_Race_Total  Senior_Managers  Professionals  Technicians  \
0          761483.0         833367.0     10534689.0    2870353.0
1            1651.0           4044.0        13505.0       5874.0
2             679.0           1854.0         7206.0       2037.0
3             382.0           1055.0         2347.0       2230.0
4              26.0             84.0          786.0        116.0

   Sales_Workers  Clericals      Craft  Operatives     Labors  Mid_Managers
0      5681336.0  6533111.0  2950753.0   5337312.0  3777568.0     7867285.0
1         7045.0    12631.0    12195.0     38015.0   159938.0        5716.0
2         4055.0     5378.0     4361.0     13319.0    85464.0        2455.0
3          724.0     3050.0     4449.0     12764.0    33742.0        1557.0
4           45.0      275.0      499.0       624.0      348.0          80.0

[5 rows x 22 columns]

In [4]:
df = pd.read_csv(r'C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Cleaned_Master\EEOC1_Master.csv')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 561371 entries, 0 to 561370
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Year              561371 non-null  int64
 1   State             519315 non-null  str
 2   County            301101 non-null  str
 3   NAICS2_Name       525862 non-null  str
 4   Male_Total        554866 non-null  float64
 5   Female_Total      554866 non-null  float64
 6   White_Total       555259 non-null  float64
 7   Black_Total       488902 non-null  float64
 8   Hisp_Total        500569 non-null  float64
 9   Asian_Total       382013 non-null  float64
 10  Amer_Ind_Total    232288 non-null  float64
 11  P_Isld_Total      103473 non-null  float64
 12  Multi_Race_Total  432651 non-null  float64
 13  Senior_Managers   330195 non-null  float64
 14  Professionals     472421 non-null  float64
 15  Technicians       390418 non-null  float64
 16  Sales_Workers     387608 non-null  float64
 17  Clericals         514240 non-null  float64
 18  Craft             391371 non-null  float64
 19  Operatives        412982 non-null  float64
 20  Labors            414196 non-null  float64
 21  Mid_Managers      301452 non-null  float64
dtypes: float64(18), int64(1), str(3)
memory usage: 94.2 MB

In [7]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
561366    False
561367    False
561368    False
561369    False
561370    False
Length: 561371, dtype: bool

In [8]:
df.dtypes

Year                  int64
State                   str
County                  str
NAICS2_Name             str
Male_Total          float64
Female_Total        float64
White_Total         float64
Black_Total         float64
Hisp_Total          float64
Asian_Total         float64
Amer_Ind_Total      float64
P_Isld_Total        float64
Multi_Race_Total    float64
Senior_Managers     float64
Professionals       float64
Technicians         float64
Sales_Workers       float64
Clericals           float64
Craft               float64
Operatives          float64
Labors              float64
Mid_Managers        float64
dtype: object

In [9]:
df.describe()

,Year,Male_Total,Female_Total,White_Total,Black_Total,Hisp_Total,Asian_Total,Amer_Ind_Total,P_Isld_Total,Multi_Race_Total,Senior_Managers,Professionals,Technicians,Sales_Workers,Clericals,Craft,Operatives,Labors,Mid_Managers
count,561371.000000,5.548660e+05,5.548660e+05,5.552590e+05,4.889020e+05,5.005690e+05,3.820130e+05,232288.000000,103473.000000,4.326510e+05,3.301950e+05,4.724210e+05,3.904180e+05,3.876080e+05,5.142400e+05,3.913710e+05,4.129820e+05,4.141960e+05,3.014520e+05
mean,2019.366909,9.277693e+03,8.756443e+03,1.053217e+04,3.112389e+03,3.214948e+03,1.796988e+03,233.047510,225.497946,5.245849e+02,4.855918e+02,4.705638e+03,1.377546e+03,2.840213e+03,2.278482e+03,1.303797e+03,2.337921e+03,1.862839e+03,4.922312e+03
std,3.039839,1.659400e+05,1.612690e+05,1.885453e+05,5.600636e+04,5.837003e+04,2.884075e+04,2973.876507,2169.969160,8.830654e+03,6.823969e+03,8.132538e+04,2.288380e+04,4.887601e+04,3.995636e+04,2.076578e+04,3.837003e+04,3.075018e+04,7.355860e+04
min,2014.000000,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000,3.000000,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00
25%,2017.000000,2.050000e+02,1.530000e+02,2.760000e+02,3.000000e+01,2.800000e+01,1.300000e+01,9.000000,10.000000,1.000000e+01,1.300000e+01,3.200000e+01,2.300000e+01,2.300000e+01,3.400000e+01,2.300000e+01,3.800000e+01,3.200000e+01,3.200000e+01
50%,2020.000000,6.340000e+02,4.880000e+02,7.810000e+02,1.330000e+02,1.180000e+02,5.200000e+01,23.000000,26.000000,3.100000e+01,3.600000e+01,1.400000e+02,8.000000e+01,1.180000e+02,1.140000e+02,8.800000e+01,1.740000e+02,1.220000e+02,1.830000e+02
75%,2022.000000,2.302000e+03,1.880000e+03,2.697000e+03,6.390000e+02,5.550000e+02,2.730000e+02,77.000000,85.000000,1.220000e+02,1.320000e+02,7.600000e+02,3.140000e+02,5.920000e+02,4.860000e+02,3.460000e+02,6.670000e+02,4.680000e+02,8.740000e+02
max,2023.000000,3.967136e+07,3.817373e+07,4.274132e+07,1.198683e+07,1.445705e+07,5.476881e+06,498361.000000,233368.000000,2.233847e+06,1.228770e+06,1.705375e+07,4.221921e+06,9.531002e+06,8.166479e+06,3.865601e+06,7.094110e+06,6.105353e+06,1.245316e+07

In [10]:
df.value_counts()

Year  State          County     NAICS2_Name                                       Male_Total  Female_Total  White_Total  Black_Total  Hisp_Total  Asian_Total  Amer_Ind_Total  P_Isld_Total  Multi_Race_Total  Senior_Managers  Professionals  Technicians  Sales_Workers  Clericals  Craft  Operatives  Labors  Mid_Managers
2014  Massachusetts  Middlesex  Professional, Scientific, and Technical Services  43900.0     26178.0       54375.0      2422.0       2377.0      9940.0       124.0           66.0          732.0             2792.0           40037.0        2845.0       4979.0         4753.0     144.0  368.0       290.0   233.0           2
                     Norfolk    Professional, Scientific, and Technical Services  4467.0      2754.0        5605.0       353.0        186.0       1011.0       6.0             6.0           50.0              256.0            3832.0         411.0        391.0          798.0      6.0    4.0         10.0    76.0            2
                     Suffolk    Professional, Scientific, and Technical Services  22210.0     21249.0       33778.0      1745.0       1509.0      5857.0       43.0            16.0          483.0             2345.0           24250.0        1368.0       861.0          5774.0     72.0   48.0        62.0    89.0            2
      New Jersey     Hudson     Professional, Scientific, and Technical Services  5369.0      2324.0        3619.0       547.0        507.0       2935.0       16.0            7.0           58.0              574.0            4093.0         676.0        132.0          484.0      42.0   146.0       22.0    4.0             2
                     Middlesex  Professional, Scientific, and Technical Services  10414.0     4918.0        5998.0       971.0        1025.0      7208.0       22.0            4.0           98.0              831.0            8894.0         759.0        428.0          1376.0     21.0   332.0       307.0   274.0           2
                                                                                                                                                                                                                                                                                                                                ..
2023  Washington     Snohomish  Health Care and Social Assistance                 936.0       3015.0        1711.0       968.0        377.0       614.0        36.0            21.0          113.0             34.0             472.0          275.0        19.0           233.0      20.0   25.0        87.0    2546.0          1
                                Accommodation and Food Services                   3843.0      5392.0        4368.0       463.0        2878.0      678.0        111.0           47.0          605.0             44.0             8.0            19.0         88.0           88.0       40.0   121.0       158.0   8048.0          1
                                Other Services (except Public Administration)     942.0       875.0         1204.0       90.0         222.0       187.0        22.0            18.0          61.0              13.0             234.0          41.0         169.0          161.0      150.0  256.0       189.0   386.0           1
                     Yakima     Retail Trade                                      1681.0      1135.0        1376.0       28.0         1232.0      33.0         63.0            3.0           75.0              15.0             42.0           86.0         1444.0         153.0      166.0  353.0       131.0   273.0           1
                                Health Care and Social Assistance                 2768.0      11432.0       5758.0       168.0        7473.0      208.0        99.0            59.0          333.0             227.0            5323.0         991.0        37.0           2185.0     56.0   69.0        273.0   4308.0          1
Name: count, Length: 17155, dtype: int64

In [11]:
df['Year'].value_counts()

Year
2023    105613
2022    103475
2021     45143
2016     44460
2019     44332
2015     44179
2018     43919
2017     43728
2014     43707
2020     42815
Name: count, dtype: int64

In [12]:
df["Male_Total"].value_counts()

Male_Total
10.0       1192
13.0       1152
11.0       1151
8.0        1122
14.0       1104
           ...
23927.0       1
73785.0       1
84153.0       1
35174.0       1
60031.0       1
Name: count, Length: 41942, dtype: int64

In [13]:
df.Male_Total

0         26728926.0
1           187857.0
2            90891.0
3            45938.0
4             2497.0
             ...
561366         869.0
561367         301.0
561368         873.0
561369         226.0
561370          12.0
Name: Male_Total, Length: 561371, dtype: float64

In [14]:
df.head()

,Year,State,County,NAICS2_Name,Male_Total,Female_Total,White_Total,Black_Total,Hisp_Total,Asian_Total,...,Multi_Race_Total,Senior_Managers,Professionals,Technicians,Sales_Workers,Clericals,Craft,Operatives,Labors,Mid_Managers
0,2014,NaN,NaN,NaN,26728926.0,24422889.0,32348361.0,7408929.0,7066158.0,3068313.0,...,761483.0,833367.0,10534689.0,2870353.0,5681336.0,6533111.0,2950753.0,5337312.0,3777568.0,7867285.0
1,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",187857.0,90345.0,86127.0,15875.0,165020.0,7013.0,...,1651.0,4044.0,13505.0,5874.0,7045.0,12631.0,12195.0,38015.0,159938.0,5716.0
2,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",90891.0,43864.0,30544.0,3682.0,95595.0,3067.0,...,679.0,1854.0,7206.0,2037.0,4055.0,5378.0,4361.0,13319.0,85464.0,2455.0
3,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",45938.0,22085.0,32517.0,9389.0,22823.0,2142.0,...,382.0,1055.0,2347.0,2230.0,724.0,3050.0,4449.0,12764.0,33742.0,1557.0
4,2014,NaN,NaN,"Agriculture, Forestry, Fishing and Hunting",2497.0,734.0,2650.0,132.0,305.0,54.0,...,26.0,84.0,786.0,116.0,45.0,275.0,499.0,624.0,348.0,80.0

In [22]:
filtered_df = df[(df['Black_Total'] >0 ) & (df['Year'] == '2023')]
filtered_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              0 non-null      int64
 1   State             0 non-null      str
 2   County            0 non-null      str
 3   NAICS2_Name       0 non-null      str
 4   Male_Total        0 non-null      float64
 5   Female_Total      0 non-null      float64
 6   White_Total       0 non-null      float64
 7   Black_Total       0 non-null      float64
 8   Hisp_Total        0 non-null      float64
 9   Asian_Total       0 non-null      float64
 10  Amer_Ind_Total    0 non-null      float64
 11  P_Isld_Total      0 non-null      float64
 12  Multi_Race_Total  0 non-null      float64
 13  Senior_Managers   0 non-null      float64
 14  Professionals     0 non-null      float64
 15  Technicians       0 non-null      float64
 16  Sales_Workers     0 non-null      float64
 17  Clericals         0 non-null      float64
 18  Craft             0 non-null      float64
 19  Operatives        0 non-null      float64
 20  Labors            0 non-null      float64
 21  Mid_Managers      0 non-null      float64
dtypes: float64(18), int64(1), str(3)
memory usage: 132.0 bytes