Here I will be cleaning the EEOC1_Master_Stacked Data Set

In [1]:
import pandas as pd
import dtale
import numpy as np

In [2]:
raw_df = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Master_Stacked.csv')

C:\Users\jfraz\AppData\Local\Temp\ipykernel_82332\1824601255.py:1: DtypeWarning: Columns (0: REGION, 1: DIVISION, 2: STATE, 3: COUNTY, 4: WHT10, 5: HISPT10, 6: MALE_TOTAL, 7: FEMALE_TOTAL, 8: TOTAL1_2, 9: WHM10, 10: WHF10) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_df = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Master_Stacked.csv')

In [3]:
# Created a copy file so when I mess up, I don't have to keep loading the original dataframe"
df = raw_df.copy()

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 561371 entries, 0 to 561370
Columns: 276 entries, NATION to YEAR
dtypes: float64(2), int64(3), object(7), str(264)
memory usage: 1.2+ GB

In [5]:
df.head()

,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,NAICS3_NAME,...,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2,YEAR
0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7118,25224,1406699,170431,135342,110903,6999,5657,20823,2014
1,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,NaN,...,24,50,3327,175,743,142,27,13,37,2014
2,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,Crop Production,...,*,25,*,*,*,98,*,*,19,2014
3,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,Animal Production and Aquaculture,...,*,7,*,92,104,17,9,*,7,2014
4,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,Forestry and Logging,...,*,*,*,5,*,*,*,*,*,2014

In [6]:
#d = dtale.show(df)
#d.open_browser()

In [7]:
#Moving the 'Year' column to the first position on the dataframe
move_columns = df.pop('YEAR')
df.insert(0, 'YEAR', move_columns)
df.head()

,YEAR,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,2014,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10881,7118,25224,1406699,170431,135342,110903,6999,5657,20823
1,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,...,85,24,50,3327,175,743,142,27,13,37
2,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,...,*,*,25,*,*,*,98,*,*,19
3,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,...,39,*,7,*,92,104,17,9,*,7
4,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,...,*,*,*,*,5,*,*,*,*,*

In [8]:
#quick check of how many rows where in some of the original data frames before being stacked
df2023 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2023.csv')
df2023.info()

C:\Users\jfraz\AppData\Local\Temp\ipykernel_82332\903303456.py:2: DtypeWarning: Columns (0: Region, 1: Division, 2: State, 3: County) have mixed types. Specify dtype option on import or set low_memory=False.
  df2023 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2023.csv')

<class 'pandas.DataFrame'>
RangeIndex: 105613 entries, 0 to 105612
Columns: 275 entries, Nation to TOMRF1_2
dtypes: float64(2), int64(2), str(271)
memory usage: 221.6 MB

In [9]:
df2014 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2014.csv')
df2014.info()

<class 'pandas.DataFrame'>
RangeIndex: 43707 entries, 0 to 43706
Columns: 275 entries, Nation to TOMRF1_2
dtypes: float64(2), int64(4), object(2), str(267)
memory usage: 91.7+ MB

C:\Users\jfraz\AppData\Local\Temp\ipykernel_82332\1575267954.py:1: DtypeWarning: Columns (0: Region, 1: Division, 2: State, 3: County, 4: WHT10, 5: TOTAL1_2) have mixed types. Specify dtype option on import or set low_memory=False.
  df2014 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2014.csv')

In [10]:
df2019 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2019.csv')
df2019.info()

<class 'pandas.DataFrame'>
RangeIndex: 44332 entries, 0 to 44331
Columns: 275 entries, Nation to TOMRF1_2
dtypes: float64(2), int64(2), object(5), str(266)
memory usage: 93.0+ MB

C:\Users\jfraz\AppData\Local\Temp\ipykernel_82332\2393504089.py:1: DtypeWarning: Columns (0: Region, 1: Division, 2: State, 3: County, 4: WHT10, 5: HISPT10, 6: MT10, 7: FT10, 8: TOTAL1_2) have mixed types. Specify dtype option on import or set low_memory=False.
  df2019 = pd.read_csv(r'c:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC_1_Data\EEOC1_2019.csv')

In [11]:
df.describe()

,YEAR,NAICS2,NAICS3,ESTABLISHMENTS,TOTAL10
count,561371.000000,525862.000000,287405.000000,5.613710e+05,5.613710e+05
mean,2019.366909,47.904688,478.318853,1.608241e+02,1.782720e+04
std,3.039839,14.540069,139.842270,3.984681e+03,3.222429e+05
min,2014.000000,11.000000,111.000000,3.000000e+00,3.000000e+00
25%,2017.000000,33.000000,336.000000,5.000000e+00,4.140000e+02
50%,2020.000000,48.000000,458.000000,1.200000e+01,1.173000e+03
75%,2022.000000,56.000000,561.000000,3.600000e+01,4.252000e+03
max,2023.000000,92.000000,928.000000,1.585519e+06,7.784510e+07

In [12]:
df.value_counts()

YEAR  NATION         REGION     DIVISION     STATE        CBSA                             COUNTY     NAICS2  NAICS2_NAME                                    NAICS3  NAICS3_NAME                                                             ESTABLISHMENTS  TOTAL10  WHT10  BLKT10  HISPT10  ASIANT10  AIANT10  NHOPIT10  TOMRT10  MALE_TOTAL  FEMALE_TOTAL  SENIOR_MANAGERS  PROFESSIONALS  TECHNICIANS  SALES_WORKERS  CLERICALS  CRAFT  OPERATIVES  LABORS  MID_MANAGERS  TOTAL1_2  WHM10  BLKM10  HISPM10  ASIANM10  AIANM10  NHOPIM10  TOMRM10  WHF10  BLKF10  HISPF10  ASIANF10  AIANF10  NHOPIF10  TOMRF10  WHT1  WHT2  WHT3  WHT4  WHT5  WHT6  WHT7  WHT8  WHT9  WHT1_2  BLKT1  BLKT2  BLKT3  BLKT4  BLKT5  BLKT6  BLKT7  BLKT8  BLKT9  BLKT1_2  HISPT1  HISPT2  HISPT3  HISPT4  HISPT5  HISPT6  HISPT7  HISPT8  HISPT9  HISPT1_2  ASIANT1  ASIANT2  ASIANT3  ASIANT4  ASIANT5  ASIANT6  ASIANT7  ASIANT8  ASIANT9  ASIANT1_2  AIANT1  AIANT2  AIANT3  AIANT4  AIANT5  AIANT6  AIANT7  AIANT8  AIANT9  AIANT1_2  NHOPIT1  NHOPIT2  NHOPIT3  NHOPIT4  NHOPIT5  NHOPIT6  NHOPIT7  NHOPIT8  NHOPIT9  NHOPIT1_2  TOMRT1  TOMRT2  TOMRT3  TOMRT4  TOMRT5  TOMRT6  TOMRT7  TOMRT8  TOMRT9  TOMRT1_2  MT1  MT2   MT3  MT4  MT5  MT6  MT7  MT8  MT9  MT1_2  FT1  FT2   FT3  FT4  FT5  FT6  FT7  FT8  FT9  FT1_2  WHM1  BLKM1  HISPM1  ASIANM1  AIANM1  NHOPIM1  TOMRM1  WHF1  BLKF1  HISPF1  ASIANF1  AIANF1  NHOPIF1  TOMRF1  WHM2  BLKM2  HISPM2  ASIANM2  AIANM2  NHOPIM2  TOMRM2  WHF2  BLKF2  HISPF2  ASIANF2  AIANF2  NHOPIF2  TOMRF2  WHM3  BLKM3  HISPM3  ASIANM3  AIANM3  NHOPIM3  TOMRM3  WHF3  BLKF3  HISPF3  ASIANF3  AIANF3  NHOPIF3  TOMRF3  WHM4  BLKM4  HISPM4  ASIANM4  AIANM4  NHOPIM4  TOMRM4  WHF4  BLKF4  HISPF4  ASIANF4  AIANF4  NHOPIF4  TOMRF4  WHM5  BLKM5  HISPM5  ASIANM5  AIANM5  NHOPIM5  TOMRM5  WHF5  BLKF5  HISPF5  ASIANF5  AIANF5  NHOPIF5  TOMRF5  WHM6  BLKM6  HISPM6  ASIANM6  AIANM6  NHOPIM6  TOMRM6  WHF6  BLKF6  HISPF6  ASIANF6  AIANF6  NHOPIF6  TOMRF6  WHM7  BLKM7  HISPM7  ASIANM7  AIANM7  NHOPIM7  TOMRM7  WHF7  BLKF7  HISPF7  ASIANF7  AIANF7  NHOPIF7  TOMRF7  WHM8  BLKM8  HISPM8  ASIANM8  AIANM8  NHOPIM8  TOMRM8  WHF8  BLKF8  HISPF8  ASIANF8  AIANF8  NHOPIF8  TOMRF8  WHM9  BLKM9  HISPM9  ASIANM9  AIANM9  NHOPIM9  TOMRM9  WHF9  BLKF9  HISPF9  ASIANF9  AIANF9  NHOPIF9  TOMRF9  WHM1_2  BLKM1_2  HISPM1_2  ASIANM1_2  AIANM1_2  NHOPIM1_2  TOMRM1_2  WHF1_2  BLKF1_2  HISPF1_2  ASIANF1_2  AIANF1_2  NHOPIF1_2  TOMRF1_2
2014  United States  Northeast  New England  Connecticut  Bridgeport-Stamford-Norwalk, CT  Fairfield  22.0    Utilities                                      221.0   Utilities                                                               9               1014     733    134     101      35        *        *         10       746         268           48               212            67           *              204        *      68          *       *             120       578    85      55       20        *        *         *        155    49      46       15        *        *         *        *     157   54    *     92    *     54    *     *     95      *      18     4      *      56     *      8      *      *      11       *       20      7       *       45      *       5       *       *       7         *        14       *        *        9        *        *        *        *        6          *       *       *       *       *       *       *       *       *       *         *        *        *        *        *        *        *        *        *        *          *       *       *       *       *       *       *       *       *       *         39   142   62   *    58   *    65   *    *    93     9    70    5    *    146  *    3    *    *    27     *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     10     12      8        *       *        *       *     8      8       6        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     20     11      *        *       *        *       *     36     34      *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *       8        4         *          *         *          *         *       3        3         *          *         *          *           1
                                                                                                      31.0    Manufacturing                                  311.0   Food Manufacturing                                                      5               1776     721    249     317      35        *        *         452      827         949           58               98             7            *              60         55     290         166     *             214       336    180     184      19        *        *         *        385    69      133      16        *        *         *        *     75    5     *     41    28    *     *     *     169     *      10     *      *      8      13     *      *      *      9        *       5       *       *       7       13      87      153     *       15        *        7        *        *        *        *        7        *        *        9          *       *       *       *       *       *       *       *       *       *         *        *        *        *        *        *        *        *        *        *          *       *       *       *       *       *       *       *       *       *         46   53    4    *    14   *    *    *    *    120    12   45    3    *    46   *    *    *    *    94     *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     5      *       *        *       *        *       *     5      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *       *        *         6          *         *          *         *       *        *         3          *         *          *           1
                                                                                                      32.0    Manufacturing                                  322.0   Paper Manufacturing                                                     4               616      416    48      116      33        *        *         *        444         172           12               240            13           *              37         59     82          94      *             59        292    39      94       *         *        *         *        124    9       22       *         *        *         *        *     206   6     *     27    33    37    21    *     55      *      10     *      *      4      5      11     17     *      *        *       9       *       *       5       20      27      45      *       *         *        *        *        *        *        *        6        10       *        *          *       *       *       *       *       *       *       *       *       *         *        *        *        *        *        *        *        *        *        *          *       *       *       *       *       *       *       *       *       *         *    157   *    *    7    *    75   64   *    51     *    83    *    *    30   *    7    30   *    8      *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     6      *       *        *       *        *       *     4      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      33      *        *       *        *       *     *      12      *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *       *        *         *          *         *          *         *       *        *         *          *         *          *           1
                                                                                                      33.0    Manufacturing                                  332.0   Fabricated Metal Product Manufacturing                                  9               1207     750    89      257      107       *        *         *        789         418           30               177            61           44             81         164    527         12      7             104       533    53      133      *         *        *         *        217    36      124      *         *        *         *        29    157   34    41    60    125   196   4     6     98      *      *      6      *      *      *      *      *      *      *        *       *       *       *       13      25      *       7       *       *         *        *        *        *        *        7        *        *        *        *          *       *       *       *       *       *       *       *       *       *         *        *        *        *        *        *        *        *        *        *          *       *       *       *       *       *       *       *       *       *         26   129   38   *    26   *    306  *    *    83     4    48    23   *    55   *    221  *    *    21     *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     3      *       *        *       *        *       *     3      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      4       *        *       *        *       *     *      9       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *       *        *         *          *         *          *         *       *        *         *          *         *          *           1
                                                                                                                                                             333.0   Machinery Manufacturing                                                 11              2883     2284   145     174      264       *        *         *        2122        761           180              1410           375          49             295        81     90          *       *             388       1705   *       *        *         *        *         *        579    *       *        *         *        *         *        167   1115  255   *     233   69    46    *     *     344     *      *      *      *      *      3      *      *      *      7        *       *       *       3       27      *       17      *       *       *         *        161      *        *        *        *        *        *        *        *          *       *       *       *       *       *       *       *       *       *         *        *        *        *        *        *        *        *        *        *          *       *       *       *       *       *       *       *       *       *         126  1090  320  *    99   *    66   *    *    290    54   320   55   *    196  *    24   *    *    98     *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *       *        *         *          *         *          *         *       *        *         *          *         *          *           1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ..
2023  United States  West       Pacific      Washington   Yakima, WA                       Yakima     55.0    Management of Companies and Enterprises        551.0   Management of Companies and Enterprises                                 17              841      161    4       657      *         8        *         9        458         383           10               26             5            33             122        7      381         117     61            79        89     *       356      *         5        *         5        72     *       301      *         3        *         4        8     17    3     14    28    3     15    15    19    39      *      *      *      *      *      *      *      *      *      *        *       8       *       18      90      *       361     97      36      39        *        *        *        *        *        *        *        *        *        *          *       *       *       *       *       *       *       4       *       *         *        *        *        *        *        *        *        *        *        *          *       *       *       *       *       *       *       *       5       *         *    14    *    14   29   *    229  76   27   51     *    12    *    19   93   *    152  41   34   28     *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      5       *        *       *        *       *     *      3       *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      6       *        *       *        *       *     *      12      *        *       *        *       *     *      21      *        *       *        *       *     *      69      *        *       *        *       *     *      *       *        *       *        *       *     *      *       *        *       *        *       *     *      215     *        *       *        *       *     *      146     *        *       *        *       *     *      59      *        *       *        *       *     *      38      *        *       *        *       8     *      17      *        *       *        *       11    *      19      *        *       *        *       *       *        26        *          *         *          *         *       *        13        *          *         *          *           1

In [13]:
df.describe(include='all')

,YEAR,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
count,561371.000000,561371,533059,528575,519315,472803,301101,525862.000000,525862,287405.000000,...,561371,561371,561371,561371,561371,561371,561371,561371,561371,561371
unique,NaN,1,4,9,51,932,1835,NaN,20,NaN,...,780,771,1783,10176,4063,4049,3581,702,748,1674
top,NaN,United States,South,South Atlantic,Texas,"New York-Newark-Jersey City, NY-NJ-PA",Washington,NaN,Manufacturing,NaN,...,*,*,*,*,*,*,*,*,*,*
freq,NaN,561371,210607,103015,34481,11529,3617,NaN,98526,NaN,...,536989,540376,487287,387007,410110,407118,465632,536994,540376,487302
mean,2019.366909,NaN,NaN,NaN,NaN,NaN,NaN,47.904688,NaN,478.318853,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.039839,NaN,NaN,NaN,NaN,NaN,NaN,14.540069,NaN,139.842270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2014.000000,NaN,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,111.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,33.000000,NaN,336.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,48.000000,NaN,458.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN,56.000000,NaN,561.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,92.000000,NaN,928.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#searching for duplicates
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
561366    False
561367    False
561368    False
561369    False
561370    False
Length: 561371, dtype: bool

In [15]:
#another check for duplicates
duplicates_only = df[df.duplicated()]
print(duplicates_only)

Empty DataFrame
Columns: [YEAR, NATION, REGION, DIVISION, STATE, CBSA, COUNTY, NAICS2, NAICS2_NAME, NAICS3, NAICS3_NAME, ESTABLISHMENTS, TOTAL10, WHT10, BLKT10, HISPT10, ASIANT10, AIANT10, NHOPIT10, TOMRT10, MALE_TOTAL, FEMALE_TOTAL, SENIOR_MANAGERS, PROFESSIONALS, TECHNICIANS, SALES_WORKERS, CLERICALS, CRAFT, OPERATIVES, LABORS, MID_MANAGERS, TOTAL1_2, WHM10, BLKM10, HISPM10, ASIANM10, AIANM10, NHOPIM10, TOMRM10, WHF10, BLKF10, HISPF10, ASIANF10, AIANF10, NHOPIF10, TOMRF10, WHT1, WHT2, WHT3, WHT4, WHT5, WHT6, WHT7, WHT8, WHT9, WHT1_2, BLKT1, BLKT2, BLKT3, BLKT4, BLKT5, BLKT6, BLKT7, BLKT8, BLKT9, BLKT1_2, HISPT1, HISPT2, HISPT3, HISPT4, HISPT5, HISPT6, HISPT7, HISPT8, HISPT9, HISPT1_2, ASIANT1, ASIANT2, ASIANT3, ASIANT4, ASIANT5, ASIANT6, ASIANT7, ASIANT8, ASIANT9, ASIANT1_2, AIANT1, AIANT2, AIANT3, AIANT4, AIANT5, AIANT6, AIANT7, AIANT8, AIANT9, AIANT1_2, NHOPIT1, NHOPIT2, NHOPIT3, NHOPIT4, ...]
Index: []

[0 rows x 276 columns]

In [16]:
df.isnull()

,YEAR,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,False,False,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
1,False,False,True,True,True,True,True,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561366,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
561367,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
561368,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
561369,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
561370,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
df.head()

,YEAR,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,2014,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10881,7118,25224,1406699,170431,135342,110903,6999,5657,20823
1,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,...,85,24,50,3327,175,743,142,27,13,37
2,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,...,*,*,25,*,*,*,98,*,*,19
3,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,...,39,*,7,*,92,104,17,9,*,7
4,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,...,*,*,*,*,5,*,*,*,*,*

In [18]:
#Replaceing the '*' values with NaN in the columns I want to make numeric. 
df.replace('*', np.nan, inplace=True)
#d = dtale.show(df)
#d.open_browser()

,YEAR,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,2014,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10881,7118,25224,1406699,170431,135342,110903,6999,5657,20823
1,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,...,85,24,50,3327,175,743,142,27,13,37
2,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,...,NaN,NaN,25,NaN,NaN,NaN,98,NaN,NaN,19
3,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,...,39,NaN,7,NaN,92,104,17,9,NaN,7
4,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,...,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561366,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,62.0,Health Care and Social Assistance,621.0,...,NaN,NaN,NaN,NaN,NaN,66,NaN,NaN,NaN,NaN
561367,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,62.0,Health Care and Social Assistance,623.0,...,NaN,NaN,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN
561368,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,72.0,Accommodation and Food Services,NaN,...,NaN,NaN,NaN,NaN,NaN,51,NaN,NaN,NaN,NaN
561369,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,81.0,Other Services (except Public Administration),NaN,...,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN
561370,2023,United States,West,Pacific,Washington,"Yakima, WA",Yakima,81.0,Other Services (except Public Administration),813.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.iloc[:, 11]

0         260632
1           1268
2            587
3            349
4             30
           ...
561366       100
561367        24
561368        62
561369        24
561370         7
Name: ESTABLISHMENTS, Length: 561371, dtype: int64

In [20]:
#I need to change all of my columns after 'Establishments' to numeric
#df.iloc[:, 11:] = pd.to_numeric(df.iloc[:, 11:], errors= 'coerce')
#df.dtypes
#df.info()

In [21]:
#The above cell didn't work. After researching, I'm trying this code instead
#df.iloc[:, 11:] = df.iloc[:, 11:].apply(pd.to_numeric, errors='coerce')
#df.dtypes
#df.info()

In [22]:
#previous code still did not work. Trying this AI corrected version instead. 
# 1. Grab the first 11 columns (leave them exactly as they are)
left_side = df.iloc[:, :11]

# 2. Grab column 11 onwards and convert them to numbers
right_side = df.iloc[:, 11:].apply(pd.to_numeric, errors='coerce')

# 3. Glue them back together side-by-side (axis=1) into a new dataframe
df = pd.concat([left_side, right_side], axis=1)

df.dtypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 561371 entries, 0 to 561370
Columns: 276 entries, YEAR to TOMRF1_2
dtypes: float64(265), int64(3), str(8)
memory usage: 1.2 GB

In [23]:
d = dtale.show(df)
d.open_browser()
df.head()

,YEAR,NATION,REGION,DIVISION,STATE,CBSA,COUNTY,NAICS2,NAICS2_NAME,NAICS3,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,2014,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10881.0,7118.0,25224.0,1406699.0,170431.0,135342.0,110903.0,6999.0,5657.0,20823.0
1,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,...,85.0,24.0,50.0,3327.0,175.0,743.0,142.0,27.0,13.0,37.0
2,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,...,NaN,NaN,25.0,NaN,NaN,NaN,98.0,NaN,NaN,19.0
3,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,...,39.0,NaN,7.0,NaN,92.0,104.0,17.0,9.0,NaN,7.0
4,2014,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,...,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN

In [25]:
df_demographic_totals = df[df.iloc[:, 2:10].isna().all(axis=1)].copy()
d = dtale.show(df_demographic_totals)
d.open_browser()
df.info()

<class 'pandas.DataFrame'>
Index: 561361 entries, 1 to 561370
Columns: 276 entries, YEAR to TOMRF1_2
dtypes: float64(265), int64(3), str(8)
memory usage: 1.2 GB

In [26]:
df.loc[:, 'CBSA']

1                NaN
2                NaN
3                NaN
4                NaN
5                NaN
             ...
561366    Yakima, WA
561367    Yakima, WA
561368    Yakima, WA
561369    Yakima, WA
561370    Yakima, WA
Name: CBSA, Length: 561361, dtype: str

In [27]:
#Looking to see if Louisville, KY is in the 'CBSA' column.
# This returns a DataFrame containing only rows where the CBSA name includes "Louisville"
louisville_data = df[df["CBSA"].str.contains("Louisville", case=False, na=False)]

# To see the specific counts for those matching names:
print(louisville_data["CBSA"].value_counts())

CBSA
Louisville/Jefferson County, KY-IN    2117
Name: count, dtype: int64

In [28]:
# 1. Isolate the national totals (Where State is blank)
df_national_baselines = df[df['STATE'].isna()].copy()

# 2. Isolate the State-level totals (Where State is NOT blank, but County is blank)
df_state_totals = df[df['STATE'].notna() & df['COUNTY'].isna()].copy()

# 3. Create your main granular dataset (Where County is NOT blank)
df_county_totals = df[df['COUNTY'].notna()].copy()

# 4. Create your main granular dataset (Where CBSA is NOT blank)
df_CBSA_total = df[df['COUNTY'].notna()].copy()

In [29]:
#d = dtale.show(df_national_baselines)
#d.open_browser()
#df.info()

In [30]:
#d = dtale.show(df_state_totals)
#d.open_browser()
#df.info()

In [31]:
#d = dtale.show(df_county_totals)
#d.open_browser()
#df.info()

In [32]:
#d = dtale.show(df_CBSA_total)
#d.open_browser()
#df.info()

In [33]:
#Isolate the Total Value Categrories by Year
df_demographic_totals = df[df.iloc[:, 2:10].isna().all(axis=1)].copy()
#d = dtale.show(df_demographic_totals)
#d.open_browser()
#df.info()

In [34]:
Computer_Folder = r'C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Cleaned_Master\'EEOC_Cleaned_Master_Stacked.csv'
df.to_csv(Computer_Folder, index=False)

In [35]:
import os

In [36]:
#Saved all of my New Data Frames to CSV
folder_path = r'C:\Users\jfraz\Code_You_Data_Analytics_Pathway\EEOC_Project\EEOC_Data\EEOC1_Cleaned_Master'

national_file = os.path.join(folder_path, 'EEOC1_National_Baselines.csv')
state_file = os.path.join(folder_path, 'EEOC1_State_Totals.csv')
county_file = os.path.join(folder_path, 'EEOC1_County_Totals.csv')
demographic_file = os.path.join(folder_path, 'EEOC1_Demographic_Totals.csv')
cbsa_file = os.path.join(folder_path, 'EEOC1_CBSA_Total.csv')

df_national_baselines.to_csv(national_file, index=False)
df_state_totals.to_csv(state_file, index=False)
df_county_totals.to_csv(county_file, index_label=False)
df_demographic_totals.to_csv(demographic_file, index=False)
df_CBSA_total.to_csv(cbsa_file, index=False)